### ISSUE TITLE
Error "cannot add relation" while applying monitoring overlay

### ISSUE THREAD

**Issue by radraw** [canonical/ubuntu.com#11662]
While trying to apply monitoring overlay on fresh installation of charmed-kubernetes 1.24 error appears:

ERROR cannot deploy bundle: cannot add relation between "kubernetes-worker:scrape" and "prometheus:juju-info": no relations found

---
*Reported from: https://ubuntu.com/kubernetes/docs/monitoring*

**Comment by radraw** [comment]
Looking at charms metadata and  guesing by interface name my fix is the following patch to original overlay yaml (on Canonical documentation page):

--- mon-canonical-doc-2022-05-31.yaml	2022-06-01 09:59:41.134469337 +0200
+++ mon-fix.yaml	2022-06-01 10:01:30.725190144 +0200
@@ -18,6 +18,6 @@
   - [kubernetes-control-plane:grafana, grafana:dashboards]
   - [prometheus:certificates, easyrsa:client]
   - [kubernetes-worker:juju-info, telegraf:juju-info]
-  - [kubernetes-worker:scrape, prometheus:juju-info]
+  - [kubernetes-worker:scrape, prometheus:scrape]
   - [etcd:grafana, grafana:dashboards]
-  - [etcd:prometheus, prometheus:scrape]
+  - [etcd:prometheus, prometheus:manual-jobs]

The second change for etcd is also required. It fixes another error (which appears after fixing kubernetes-worker relation):

ERROR cannot deploy bundle: cannot add relation between "etcd:prometheus" and "prometheus:scrape": no relations found

After applying this patch deployment of overlay command works fine and I see some data in Grafana dashboards.

**Comment by pmahnke** [comment]
@evilnick can you look at this?

**Comment by sowasred2012** [comment]
@evilnick any chance you could take a look at this please?

**Comment by evilnick** [comment]
This issue was fixed some time ago by changes to the monitoring stack

**Comment by radraw** [comment]
I see this issue is closed, but the error still persists. I just tried with current version of charmed-kubernetes.

**Comment by evilnick** [comment]
@radraw apologies, I was informed it was changed but those don't seem to be live yet. I will patch the docs for now
