### ISSUE TITLE
Ubuntu Security Notices "latest notices" wrong sort order

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu.com#13956]
Hello, The Ubuntu Security Notices page is currently showing USN 1-1 as the very first result. I believe it would be more useful to show the most recent USNs at the top of the list rather than one from twenty years ago.

![usn-latest](https://github.com/canonical/ubuntu.com/assets/5447148/1dbc95bd-fd71-460d-a1d2-617c3efc9358)

Thanks

---
*Reported from: https://ubuntu.com/security/notices*

**Comment by eslerm** [comment]
Users have begun to ask s@u.c about this issue.

**Comment by mtruj013** [comment]
@setharnold, @eslerm this has been fixed now, thanks for reporting! 
![image](https://github.com/canonical/ubuntu.com/assets/17607612/f9121585-aece-4530-942c-9eb012cb5c5f)

**Comment by sudhackar** [comment]
Sorry to ping on closed issue - We still have a problem - the pagination still fetches `USN-12-1` on https://ubuntu.com/security/notices?offset=10 - the first page for example
