### ISSUE TITLE
Clicking on 'Get ubuntu Pro' button gives 502 Bad Gateway here

### ISSUE THREAD

**Issue by nikolam** [canonical/ubuntu.com#15925]
### Summary

On the page:  https://ubuntu.com/pro/subscribe  
When i click on the green "Register" button,  
I get 502 Bad Gateway message here,   on https://ubuntu.com/login?next=/pro/dashboard? .  So I am unable to enroll in Ubuntu Pro. 
Browser Firefox 146.0.1 from Mozilla site on Xubuntu 24.04.3 LTS .
Location: Europe , Serbia, Belgrade (MTS internet provider) 

### Steps to reproduce the behavior

Go to https://ubuntu.com/pro/subscribe 
Click on  "Register" button 
Result: 
Getting https://ubuntu.com/login?next=/pro/dashboard? 
with 502 Bad Gateway message

### Expected behavior

It is expected to get Ubuntu Pro registration page and continue with Ubuntu Pro registration. 

### Browser/device details

Desktop PC with Intel i5 8500,  Browser Firefox 146.0.1 from Mozilla site on Xubuntu 24.04.3 LTS 

### Reported from

https://ubuntu.com/pro/subscribe

**Comment by AZEEMAZAM1** [comment]
Hi @nikolam, I'd like to help investigate and fix this issue. 

I'm a junior developer with experience in Python/Django and web development. I can reproduce the bug and track down the 502 Bad Gateway error in the login redirect flow.

I'll:
1. Fork the repository and set up the local development environment
2. Reproduce the issue locally
3. Debug the `/login?next=/pro/dashboard` endpoint
4. Identify the root cause (likely a routing or backend service issue)
5. Submit a PR with the fix and tests

I'll update here once I have more findings. Thanks!

**Comment by AZEEMAZAM1** [comment]
**Update**: I've investigated the codebase and found some important details:

## Findings:

1. **The failing URL**: `https://ubuntu.com/login?next=/pro/dashboard` 
   - This is the redirect target after clicking "Register" button on `/pro/subscribe`

2. **Code Reference**: In `templates/pro/tutorial.html` (line 298), there's a similar login redirect pattern:
   ```html
   <a href="#">https://login.ubuntu.com/invalidate-email/{YOUR_TOKEN_HERE}/{YOUR_EMAIL_HERE}</a>
   ```

3. **The likely issue**: The 502 Bad Gateway suggests the `/login` endpoint may be:
   - Misconfigured in routing
   - Missing backend service connection  
   - Or the `next=/pro/dashboard` parameter is malformed

## Next steps:
- Check if `/login` endpoint is properly configured in Flask routes
- Verify backend authentication service is running
- Test if the issue is specific to the `?next=` query parameter

Will fork the repo and test locally to confirm the root cause.

**Comment by AZEEMAZAM1** [comment]
**Root cause found** in `webapp/login.py`:

The `/login` route (line 71-77 in `login_handler()`) redirects using `open_id.get_next_url()` after authentication. This causes the 502 when `/login?next=/pro/dashboard` is accessed.

**The issue**: The `/login` endpoint likely doesn't exist as a Flask route, or the OpenID redirect is misconfigured for the Pro dashboard flow.

I'll fork the repo and create a fix that either:
1. Adds the missing `/login` route, or  
2. Fixes the redirect URL generation for Pro dashboard

Working on the PR now.

**Comment by AZEEMAZAM1** [comment]
## Final Root Cause Analysis & Solution

After thorough investigation of the codebase, I've identified the **actual root cause** of the 502 Bad Gateway error:

### Root Cause
The issue is NOT that `/login` route is missing (it exists in `webapp/app.py` line ~1400). The 502 error occurs because:

**The `login_handler()` function in `webapp/login.py` (lines 71-107) makes an API call to fetch a macaroon from `contracts.canonical.com` without proper error handling:**

```python
response = session.request(
    method="get", url=f"{api_url}/v1/canonical-sso-macaroon"
)
```

If this API call fails (timeout, service down, or network issues), it causes an unhandled exception that results in a 502 Bad Gateway error.

### The Fix
I'll create a PR that adds proper error handling around the API call and provides a user-friendly error page when the authentication service is unavailable.

**Key changes:**
1. Wrap the macaroon API call in try-except block
2. Handle timeout and connection errors gracefully  
3. Return a proper error message to users instead of 502
4. Add logging for debugging

This will prevent the 502 error and give users a clear message about what's wrong.

Working on the PR now - will link it here shortly!

**Comment by mtruj013** [comment]
@abhigyanghosh30 could you take a look please?

**Comment by abhigyanghosh30** [comment]
@nikolam You could try clearing your cookies for ubuntu.com and trying to login again. We are working on a permanent fix for this in the meantime.

**Comment by jagadish-7** [comment]
Yes @abhigyanghosh30 Clearing cookies fixes the issue. 

I was able to reproduce it when I was redirected to the login screen and clicked “Cancel” instead of logging in.

<img width="1915" height="982" alt="Image" src="https://github.com/user-attachments/assets/1fed3915-b70b-481a-adf6-4fe494843cab" />

Let me know if are working on this, if not I can proceed with a fix. 

Thanks

**Comment by muhammad-ali-pk** [comment]
@abhigyanghosh30 Was there ever a permanent fix for this, and can this issue be closed?

**Comment by abhigyanghosh30** [comment]
We tried to but it didn't fix things. Reducing the cookie size was the suggested fix but it didn't help

**Comment by kuci-JK** [comment]
The login page is broken for me as well. I am trying to get to the Ubuntu Pro dashboard.

Steps to reproduce:
1. go to https://ubuntu.com (or https://ubuntu.com/pro/dashboard)
2. click Sign in
3. 502 Bad Gateway

Chrome, Ubuntu 26.04

Clearing cookies and site data did not help, nor did trying in anonymous window.

Is there any fix available?

**Comment by gh0st-network** [comment]
> The login page is broken for me as well. I am trying to get to the Ubuntu Pro dashboard.
> 
> Steps to reproduce:
> 
> 1. go to https://ubuntu.com (or https://ubuntu.com/pro/dashboard)
> 2. click Sign in
> 3. 502 Bad Gateway
> 
> Chrome, Ubuntu 26.04
> 
> Clearing cookies and site data did not help, nor did trying in anonymous window.
> 
> Is there any fix available?

The login screen and subsequent pages behind the login are down for me as well.

**Comment by tristan-k** [comment]
+1

**Comment by haider-ittefaq** [comment]
Getting the same error also checked the Ubuntu Status Page no update their as well.

**Comment by abhigyanghosh30** [comment]
Hi, the issue should be resolved now

**Comment by stanleyowen** [comment]
Tried clearing the cookies but still won't work on my end, anyone facing the same issue?

**Comment by gh0st-network** [comment]
> Tried clearing the cookies but still won't work on my end, anyone facing the same issue?

Issue still persists for me. Tested on 2 devices, different Internet lines.

**Comment by TimTamno1** [comment]
Same issue here, clearing cookies does not work either

**Comment by user-25806946** [comment]
I'm experiencing the same issue.

**Comment by user-25806946** [comment]
> I'm experiencing the same issue.

<img width="1508" height="840" alt="Image" src="https://github.com/user-attachments/assets/e505cc5a-e02a-4692-be71-62402eb410d9" />

**Comment by bones78** [comment]
same issue here

**Comment by haider-ittefaq** [comment]
> Hi, the issue should be resolved now

Hi, still getting the same issue on multiple devices even tried in the private mode or incognito mode even tried on different mobile devices but still the issue.

**Comment by Satal** [comment]
Anyone else notice the nginx version? I could be mistaken but that looks pretty out of date...

<img width="343" height="124" alt="Image" src="https://github.com/user-attachments/assets/35ddd4aa-9d84-4db1-b2b1-fe177ef010f7" />

**Comment by haider-ittefaq** [comment]
**The app code is healthy. The failure is a response-header-size overflow at a proxy tier in front of the app.**

`/login` response carries ~17 KB of headers (two giant CSP headers + macaroon session `set-cookie` + OpenID `location`). That overflows the nginx `proxy_buffer_size` of whatever tier emits the stock `nginx/1.14.0 (Ubuntu)` 502 page. The regression began the same day the CSP audit (#16626) landed (Jul 23), which pushed header size past the 16k buffer fix from Jul 16 (#16603).

- **#16641 / #16644 (contracts trailing slash)** these fixed the wrong thing. The double slash in `//v1/...` only causes a harmless redirect, and the Python code follows that redirect automatically. I tested the macaroon endpoint with both URL styles and it returns 200 every time.
- **32k buffer in `konf/site.yaml`** this fix lives in the wrong place. Look at the 502 error page itself: it has none of the app's normal headers (no `x-cache-status`, no CSP) and says `server: nginx/1.14.0 (Ubuntu)` a very old nginx version. That means the error comes from a separate proxy server sitting in front of everything (Canonical's cache/frontend layer), not from the app or its Kubernetes ingress. This repo can only configure the ingress, so raising the buffer here never reaches the server that is actually dropping the response.

Cookieless requests also 502 the overflow is in the **response** headers. Clearing cookies (the #15925-era fix) does nothing now.

Fix: raise `proxy_buffer_size`/`proxy_buffers` (≥32k) on the frontend/content-cache tier for the ubuntu.com vhost and double-check the deployed konf actually supports  nginxProxyBufferSize  (canonical/konf#53), otherwise the 32k is silently ignored

I might be totally wrong here, but these are my findings in case they help

**Comment by bones78** [comment]
now it works, thanks!

**Comment by Onibenjo** [comment]
Closing this issue as this has been resolved now
Thanks
