### ISSUE TITLE
Feature parity with HTML5 client-side form validation

### ISSUE THREAD

**Issue by nottrobin** [canonical/ubuntu.com#3942]
In e.g. https://www.ubuntu.com/engage/iot-business-model, there is no client-side validation for the "Phone number" (`type="tel"`) field.

We've turned off HTML5 validation with novalidate="novalidate", but then we don't implement our own validation for the "phone number" type="tel" field.

We should at least have feature parity with HTML5 validation for known filetypes. In this day and age, wouldn't it be possible to re-enable HTML5 validation and style it as we need? Or if not, we should implement feature parity.

**Comment by anasereijo** [comment]
@anthonydillon is this something we can add to small tasks?

**Comment by anthonydillon** [comment]
@anasereijo yea sure but would say we might have enough the iteration.

**Comment by pmahnke** [comment]
this was fixed with g-recaptcha work

**Comment by nottrobin** [comment]
This issue still exists at https://www.ubuntu.com/engage/iot-business-model

**Comment by anthonydillon** [comment]
We have replaced telephone form fields with a module now.
